name: test_crud_sw
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Rest
  dio: ^5.4.3+1

  # Manager
  provider: ^6.1.2
  auto_injector: ^2.0.0

  # Storage
  flutter_secure_storage: ^9.0.0

  # Utils
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
